### ISSUE TITLE
Test segfault on ppc64le

### ISSUE THREAD

**Issue by eclipseo** [pengsrc/go-utils#6]
with Golang 1.12-0.rc1

```
Testing: "/builddir/build/BUILD/go-shared-1ef04317652833067e47e2ee9815f1f254a7a1da/_build/src/github.com/pengsrc/go-shared/convert"
+ GOPATH=/builddir/build/BUILD/go-shared-1ef04317652833067e47e2ee9815f1f254a7a1da/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
unexpected fault address 0xffffffffffd07578
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x3 addr=0xffffffffffd07578 pc=0x13320d4c4]
goroutine 22 [running]:
runtime.throw(0x13321c57f, 0x5)
	/usr/lib/golang/src/runtime/panic.go:617 +0x68 fp=0xc0000afe58 sp=0xc0000afe18 pc=0x132fcca98
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:397 +0x464 fp=0xc0000afe98 sp=0xc0000afe58 pc=0x132fe5324
time.(*Time).unixSec(...)
	/usr/lib/golang/src/time/time.go:176
time.Time.Unix(...)
	/usr/lib/golang/src/time/time.go:1146
github.com/pengsrc/go-shared/convert.TimeToTimestamp(0x0, 0xecf59cff8, 0xc000092600, 0xf)
	/builddir/build/BUILD/go-shared-1ef04317652833067e47e2ee9815f1f254a7a1da/_build/src/github.com/pengsrc/go-shared/convert/time.go:44 +0x74 fp=0xc0000afef0 sp=0xc0000afeb8 pc=0x13320d4c4
github.com/pengsrc/go-shared/convert.TestTimeToTimestamp(0xc000104400)
	/builddir/build/BUILD/go-shared-1ef04317652833067e47e2ee9815f1f254a7a1da/_build/src/github.com/pengsrc/go-shared/convert/time_test.go:59 +0xe0 fp=0xc0000aff70 sp=0xc0000afef0 pc=0x133210d90
testing.tRunner(0xc000104400, 0x1333b1d70)
	/usr/lib/golang/src/testing/testing.go:865 +0xdc fp=0xc0000affb0 sp=0xc0000aff70 pc=0x13307a0ac
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_ppc64x.s:856 +0x4 fp=0xc0000affb0 sp=0xc0000affb0 pc=0x132fffaa4
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:916 +0x304
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000104400, 0x1332205fc, 0x13, 0x1333b1d70, 0x133577f01)
	/usr/lib/golang/src/testing/testing.go:917 +0x320
testing.runTests.func1(0xc000104000)
	/usr/lib/golang/src/testing/testing.go:1157 +0x8c
testing.tRunner(0xc000104000, 0xc0000addd8)
	/usr/lib/golang/src/testing/testing.go:865 +0xdc
testing.runTests(0xc00009c380, 0x133577f60, 0x2d, 0x2d, 0x0)
	/usr/lib/golang/src/testing/testing.go:1155 +0x2a0
testing.(*M).Run(0xc000102000, 0x0)
	/usr/lib/golang/src/testing/testing.go:1072 +0x174
main.main()
	_testmain.go:130 +0x150
exit status 2
FAIL	github.com/pengsrc/go-shared/convert	0.014s
```

**Comment by eclipseo** [comment]
Fixed in Golang 1.12.
